# Generated by Django 5.0.4 on 2024-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('job_function', models.CharField(choices=[('CM', 'campaign management'), ('CRM', 'CRM Administrations'), ('ED', 'Email Development'), ('Emp', 'Employee'), ('PT', 'Partner')], default=True, max_length=20)),
                ('training_date', models.DateField()),
                ('dietary_requirement', models.CharField(max_length=20)),
                ('exceptions', models.CharField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
